apiVersion: v1
kind: Secret
metadata:
  name: tubester-api-secrets
  namespace: tubester
type: Opaque
stringData:
  ConnectionStrings__TubesterDb: "SECRET"
  GoogleAuth__ClientId: "SECRET"
  GoogleAuth__ClientSecret: "SECRET"
  YouTubeApi__ApiKey: "SECRET"
  Hangfire__AdminEmails__0: "SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: tubester
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "KUBAAK",
          "password": "YOUR_GITHUB_PAT",
          "auth": "BASE64_OF_KUBAAK_COLON_YOUR_GITHUB_PAT"
        }
      }
    }