apiVersion: apps/v1
kind: Deployment
metadata:
  name: tubester-worker
  namespace: tubester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tubester-worker
  template:
    metadata:
      labels:
        app: tubester-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worker
          image: ghcr.io/kubaak/tubester-worker:latest
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
          envFrom:
            - secretRef:
                name: tubester-api-secrets
          securityContext:
            runAsNonRoot: true
            runAsUser: 1654
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
