apiVersion: v1
kind: ConfigMap
metadata:
  name: tubester-config
  namespace: tubester
data:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_ENVIRONMENT: "Production"
  Observability__Enabled: "true"
  Observability__Prometheus__Enabled: "true"
  Observability__Seq__Enabled: "false"