apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tubester-worker
  namespace: monitoring
  labels:
    app: tubester-worker
spec:
  namespaceSelector:
    matchNames:
      - tubester
  selector:
    matchLabels:
      app: tubester-worker
  endpoints:
    - port: http
      path: /metrics
      interval: 30s