apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tubester-api
  namespace: monitoring
  labels:
    app: tubester-api
spec:
  namespaceSelector:
    matchNames:
      - tubester
  selector:
    matchLabels:
      app: tubester-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s