<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Tubester.Persistence</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.NetCore" Version="1.8.23" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tubester.Abstractions\Tubester.Abstractions.csproj"/>
        <ProjectReference Include="..\Tubester.Domain\Tubester.Domain.csproj"/>
    </ItemGroup>

</Project>
