<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>YouTubester.Persistence</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.NetCore" Version="1.8.22"/>
        <PackageReference Include="Hangfire.PostgreSql" Version="1.20.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\YouTubester.Abstractions\YouTubester.Abstractions.csproj"/>
        <ProjectReference Include="..\YouTubester.Domain\YouTubester.Domain.csproj"/>
    </ItemGroup>

</Project>
